;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="AI.Agrro",DevComment="")
+GameplayTagList=(Tag="AI.Agrro.Agressive",DevComment="")
+GameplayTagList=(Tag="AI.Agrro.Calm",DevComment="")
+GameplayTagList=(Tag="AI.Event.OnLostTarget",DevComment="")
+GameplayTagList=(Tag="AI.Events.HearNoise",DevComment="")
+GameplayTagList=(Tag="AI.Events.OnSeeAndComfirmTarget",DevComment="")
+GameplayTagList=(Tag="AI.Events.OnSeeAndNotComfirmedTarget",DevComment="")
+GameplayTagList=(Tag="AI.Events.OnUnawareOfTarget",DevComment="")
+GameplayTagList=(Tag="AI.Sense",DevComment="")
+GameplayTagList=(Tag="AI.Sense.Hear",DevComment="")
+GameplayTagList=(Tag="AI.Sense.Hear.Gunshot",DevComment="")
+GameplayTagList=(Tag="AI.Sense.NoLongerSee",DevComment="")
+GameplayTagList=(Tag="AI.Sense.NoLongerSee.Guard",DevComment="")
+GameplayTagList=(Tag="AI.Sense.NoLongerSee.Player",DevComment="")
+GameplayTagList=(Tag="AI.Sense.See.Guard",DevComment="")
+GameplayTagList=(Tag="AI.Sense.See.Player",DevComment="")

